In [ ]:
import numpy as np
import cv2
import os

In [ ]:
images = []
targets = []

In [ ]:
Eimages=[]
Etargets=[]

In [ ]:
Aimages=[]
Atargets=[]

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/0-2"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(0)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/3-6"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(1)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/7-11"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(2)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/12-16"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(3)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/17-21"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(4)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/22-27"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(5)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/28-35"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(6)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/36-43"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(7)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/44-50"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(8)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/51-55"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(9)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/56-60"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(10)

In [ ]:
#Age
import cv2
import os

folder="model-best/Ages/60+"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Aimages.append(resized_img)
        Atargets.append(11)

In [ ]:
#Emotions
import cv2
import os

folder="model-best/images/images/train/neutral"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Eimages.append(resized_img)
        Etargets.append(0)

In [ ]:
#Emotions
import cv2
import os

folder="model-best/images/images/train/happy"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Eimages.append(resized_img)
        Etargets.append(1)

In [ ]:
#Emotions
import cv2
import os

folder="model-best/images/images/train/sad"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        Eimages.append(resized_img)
        Etargets.append(2)

In [ ]:
import cv2
import os

folder="model-best/Training/male"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        images.append(resized_img)
        targets.append(0)

images

[array([[ 13,  12,  11, ...,  38,  40,  34],
        [ 13,  12,  11, ...,  38,  39,  39],
        [ 12,  12,  11, ...,  34,  46,  50],
        ...,
        [144, 138, 135, ...,   1,   1,   0],
        [144, 139, 137, ...,   0,   1,   0],
        [143, 140, 141, ...,   0,   0,   0]], dtype=uint8),
 array([[ 69,  72,  75, ..., 108, 104,  98],
        [ 66,  69,  72, ..., 106, 102,  95],
        [ 62,  65,  70, ..., 105, 101,  94],
        ...,
        [  3,   4,   5, ...,  19,  22,  26],
        [  2,   3,   4, ...,  22,  25,  29],
        [  2,   3,   3, ...,  24,  24,  26]], dtype=uint8),
 array([[ 24,  15,  24, ...,  66,  54,  71],
        [ 22,  19,  30, ...,  74,  65,  46],
        [ 35,  24,  27, ...,  76,  75,  67],
        ...,
        [136, 140, 140, ..., 124, 154, 198],
        [133, 141, 146, ..., 143, 188, 246],
        [139, 145, 151, ..., 165, 220, 233]], dtype=uint8),
 array([[197, 164, 140, ..., 162, 160, 158],
        [195, 160, 137, ..., 163, 164, 163],
        [177, 14

In [ ]:
folder="model-best/Training/female"
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    if img is not None:

        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        images.append(resized_img)
        targets.append(1)

images

[array([[ 13,  12,  11, ...,  38,  40,  34],
        [ 13,  12,  11, ...,  38,  39,  39],
        [ 12,  12,  11, ...,  34,  46,  50],
        ...,
        [144, 138, 135, ...,   1,   1,   0],
        [144, 139, 137, ...,   0,   1,   0],
        [143, 140, 141, ...,   0,   0,   0]], dtype=uint8),
 array([[ 69,  72,  75, ..., 108, 104,  98],
        [ 66,  69,  72, ..., 106, 102,  95],
        [ 62,  65,  70, ..., 105, 101,  94],
        ...,
        [  3,   4,   5, ...,  19,  22,  26],
        [  2,   3,   4, ...,  22,  25,  29],
        [  2,   3,   3, ...,  24,  24,  26]], dtype=uint8),
 array([[ 24,  15,  24, ...,  66,  54,  71],
        [ 22,  19,  30, ...,  74,  65,  46],
        [ 35,  24,  27, ...,  76,  75,  67],
        ...,
        [136, 140, 140, ..., 124, 154, 198],
        [133, 141, 146, ..., 143, 188, 246],
        [139, 145, 151, ..., 165, 220, 233]], dtype=uint8),
 array([[197, 164, 140, ..., 162, 160, 158],
        [195, 160, 137, ..., 163, 164, 163],
        [177, 14

In [ ]:
len(images), len(targets)

(47009, 47009)

In [ ]:
#Emotions
len(Eimages), len(Etargets)

(17087, 17087)

In [ ]:
#Age
len(Aimages), len(Atargets)

(9766, 9766)

In [ ]:
images

[array([[ 13,  12,  11, ...,  38,  40,  34],
        [ 13,  12,  11, ...,  38,  39,  39],
        [ 12,  12,  11, ...,  34,  46,  50],
        ...,
        [144, 138, 135, ...,   1,   1,   0],
        [144, 139, 137, ...,   0,   1,   0],
        [143, 140, 141, ...,   0,   0,   0]], dtype=uint8),
 array([[ 69,  72,  75, ..., 108, 104,  98],
        [ 66,  69,  72, ..., 106, 102,  95],
        [ 62,  65,  70, ..., 105, 101,  94],
        ...,
        [  3,   4,   5, ...,  19,  22,  26],
        [  2,   3,   4, ...,  22,  25,  29],
        [  2,   3,   3, ...,  24,  24,  26]], dtype=uint8),
 array([[ 24,  15,  24, ...,  66,  54,  71],
        [ 22,  19,  30, ...,  74,  65,  46],
        [ 35,  24,  27, ...,  76,  75,  67],
        ...,
        [136, 140, 140, ..., 124, 154, 198],
        [133, 141, 146, ..., 143, 188, 246],
        [139, 145, 151, ..., 165, 220, 233]], dtype=uint8),
 array([[197, 164, 140, ..., 162, 160, 158],
        [195, 160, 137, ..., 163, 164, 163],
        [177, 14

In [ ]:
Eimages

[array([[ 46,  45,  43, ...,  38,  50,  55],
        [ 45,  44,  42, ...,  39,  51,  57],
        [ 42,  42,  40, ...,  39,  55,  62],
        ...,
        [237, 237, 239, ..., 138, 126, 121],
        [235, 235, 237, ..., 151, 143, 139],
        [234, 234, 236, ..., 157, 150, 147]], dtype=uint8),
 array([[58, 58, 58, ..., 40, 43, 44],
        [58, 58, 59, ..., 40, 42, 43],
        [59, 58, 58, ..., 40, 42, 42],
        ...,
        [39, 38, 35, ..., 27, 27, 27],
        [38, 37, 35, ..., 29, 29, 29],
        [38, 37, 35, ..., 30, 30, 30]], dtype=uint8),
 array([[ 85,  88,  95, ...,  71,  67,  65],
        [ 84,  87,  95, ...,  73,  69,  67],
        [ 81,  84,  93, ...,  78,  75,  73],
        ...,
        [149, 151, 153, ..., 170, 183, 189],
        [154, 154, 152, ..., 170, 183, 188],
        [157, 155, 151, ..., 170, 182, 188]], dtype=uint8),
 array([[240, 240, 240, ...,  66,  54,  49],
        [240, 240, 240, ...,  66,  55,  50],
        [240, 240, 240, ...,  66,  57,  52],
       

In [ ]:
Aimages

[array([[123, 128, 135, ..., 180, 175, 174],
        [124, 128, 134, ..., 178, 174, 173],
        [125, 129, 134, ..., 178, 174, 174],
        ...,
        [184, 186, 187, ...,   0,   0,   0],
        [187, 187, 187, ...,   0,   0,   0],
        [187, 184, 184, ...,   0,   0,   0]], dtype=uint8),
 array([[160, 159, 157, ...,  33,  30,  28],
        [159, 160, 159, ...,  36,  34,  32],
        [160, 162, 162, ...,  40,  36,  33],
        ...,
        [168, 168, 168, ..., 204, 203, 204],
        [168, 168, 168, ..., 206, 205, 203],
        [168, 168, 168, ..., 198, 196, 193]], dtype=uint8),
 array([[162, 163, 165, ..., 192, 187, 186],
        [163, 163, 166, ..., 192, 187, 186],
        [161, 162, 164, ..., 193, 188, 187],
        ...,
        [239, 240, 241, ..., 212, 209, 203],
        [238, 239, 241, ..., 208, 203, 199],
        [237, 239, 242, ..., 206, 201, 200]], dtype=uint8),
 array([[104, 194, 194, ..., 145, 144, 143],
        [105, 196, 196, ..., 145, 143, 144],
        [104, 19

In [ ]:
images[0]

array([[ 13,  12,  11, ...,  38,  40,  34],
       [ 13,  12,  11, ...,  38,  39,  39],
       [ 12,  12,  11, ...,  34,  46,  50],
       ...,
       [144, 138, 135, ...,   1,   1,   0],
       [144, 139, 137, ...,   0,   1,   0],
       [143, 140, 141, ...,   0,   0,   0]], dtype=uint8)

In [ ]:
images = np.array(images)/255.0

In [ ]:
#Emotions
Eimages = np.array(Eimages)/255.0

In [ ]:
#Ages
Aimages = np.array(Aimages)/255.0

In [ ]:
images

array([[[0.05098039, 0.04705882, 0.04313725, ..., 0.14901961,
         0.15686275, 0.13333333],
        [0.05098039, 0.04705882, 0.04313725, ..., 0.14901961,
         0.15294118, 0.15294118],
        [0.04705882, 0.04705882, 0.04313725, ..., 0.13333333,
         0.18039216, 0.19607843],
        ...,
        [0.56470588, 0.54117647, 0.52941176, ..., 0.00392157,
         0.00392157, 0.        ],
        [0.56470588, 0.54509804, 0.5372549 , ..., 0.        ,
         0.00392157, 0.        ],
        [0.56078431, 0.54901961, 0.55294118, ..., 0.        ,
         0.        , 0.        ]],

       [[0.27058824, 0.28235294, 0.29411765, ..., 0.42352941,
         0.40784314, 0.38431373],
        [0.25882353, 0.27058824, 0.28235294, ..., 0.41568627,
         0.4       , 0.37254902],
        [0.24313725, 0.25490196, 0.2745098 , ..., 0.41176471,
         0.39607843, 0.36862745],
        ...,
        [0.01176471, 0.01568627, 0.01960784, ..., 0.0745098 ,
         0.08627451, 0.10196078],
        [0.0

In [ ]:
images = np.resize(images, (47009, 100, 100, 1))

In [ ]:
#Emotions
Eimages = np.resize(Eimages, (17087, 100, 100, 1))

In [ ]:
#Age
Aimages = np.resize(Aimages, (9766, 100, 100, 1))

In [ ]:
images

array([[[[0.05098039],
         [0.04705882],
         [0.04313725],
         ...,
         [0.14901961],
         [0.15686275],
         [0.13333333]],

        [[0.05098039],
         [0.04705882],
         [0.04313725],
         ...,
         [0.14901961],
         [0.15294118],
         [0.15294118]],

        [[0.04705882],
         [0.04705882],
         [0.04313725],
         ...,
         [0.13333333],
         [0.18039216],
         [0.19607843]],

        ...,

        [[0.56470588],
         [0.54117647],
         [0.52941176],
         ...,
         [0.00392157],
         [0.00392157],
         [0.        ]],

        [[0.56470588],
         [0.54509804],
         [0.5372549 ],
         ...,
         [0.        ],
         [0.00392157],
         [0.        ]],

        [[0.56078431],
         [0.54901961],
         [0.55294118],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       [[[0.27058824],
         [0.28235294],
         [0.29

In [ ]:
Eimages

array([[[[0.18039216],
         [0.17647059],
         [0.16862745],
         ...,
         [0.14901961],
         [0.19607843],
         [0.21568627]],

        [[0.17647059],
         [0.17254902],
         [0.16470588],
         ...,
         [0.15294118],
         [0.2       ],
         [0.22352941]],

        [[0.16470588],
         [0.16470588],
         [0.15686275],
         ...,
         [0.15294118],
         [0.21568627],
         [0.24313725]],

        ...,

        [[0.92941176],
         [0.92941176],
         [0.9372549 ],
         ...,
         [0.54117647],
         [0.49411765],
         [0.4745098 ]],

        [[0.92156863],
         [0.92156863],
         [0.92941176],
         ...,
         [0.59215686],
         [0.56078431],
         [0.54509804]],

        [[0.91764706],
         [0.91764706],
         [0.9254902 ],
         ...,
         [0.61568627],
         [0.58823529],
         [0.57647059]]],


       [[[0.22745098],
         [0.22745098],
         [0.22

In [ ]:
Aimages

array([[[[0.48235294],
         [0.50196078],
         [0.52941176],
         ...,
         [0.70588235],
         [0.68627451],
         [0.68235294]],

        [[0.48627451],
         [0.50196078],
         [0.5254902 ],
         ...,
         [0.69803922],
         [0.68235294],
         [0.67843137]],

        [[0.49019608],
         [0.50588235],
         [0.5254902 ],
         ...,
         [0.69803922],
         [0.68235294],
         [0.68235294]],

        ...,

        [[0.72156863],
         [0.72941176],
         [0.73333333],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.73333333],
         [0.73333333],
         [0.73333333],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.73333333],
         [0.72156863],
         [0.72156863],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       [[[0.62745098],
         [0.62352941],
         [0.61

In [ ]:
from keras.utils import np_utils

In [ ]:
targets[-10:]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
targets = np_utils.to_categorical(targets)

In [ ]:
#Emotions
Etargets = np_utils.to_categorical(Etargets)

In [ ]:
#Age
Atargets = np_utils.to_categorical(Atargets)

In [ ]:
targets

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [ ]:
Etargets

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [ ]:
Atargets

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(images, targets)

In [ ]:
#Emotions
EX_train, EX_test, EY_train, EY_test = train_test_split(Eimages, Etargets)

In [ ]:
#Age
AX_train, AX_test, AY_train, AY_test = train_test_split(Aimages, Atargets)

In [ ]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((35256, 100, 100, 1), (11753, 100, 100, 1), (35256, 2), (11753, 2))

In [ ]:
#Emotions
EX_train.shape, EX_test.shape, EY_train.shape, EY_test.shape

((12815, 100, 100, 1), (4272, 100, 100, 1), (12815, 3), (4272, 3))

In [ ]:
#Age
AX_train.shape, AX_test.shape, AY_train.shape, AY_test.shape

((7324, 100, 100, 1), (2442, 100, 100, 1), (7324, 12), (2442, 12))

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Activation, Dropout
from keras.optimizers import SGD
from keras.callbacks import ModelCheckpoint

In [ ]:
model = Sequential()

In [ ]:
Emodel = Sequential()

In [ ]:
Amodel = Sequential()

In [ ]:
model.add(Conv2D(200, (3,3), input_shape=(100, 100, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(100, (3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.3))
model.add(Flatten())

model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
#Emotions
Emodel.add(Conv2D(200, (3,3), input_shape=(100, 100, 1)))
Emodel.add(Activation('relu'))
Emodel.add(MaxPooling2D(pool_size=(2, 2)))

Emodel.add(Conv2D(100, (3,3)))
Emodel.add(Activation('relu'))
Emodel.add(MaxPooling2D(pool_size=(2, 2)))

Emodel.add(Dropout(0.3))
Emodel.add(Flatten())

Emodel.add(Dense(50, activation='relu'))
Emodel.add(Dense(3, activation='softmax'))

Emodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
#Age
Amodel.add(Conv2D(200, (3,3), input_shape=(100, 100, 1)))
Amodel.add(Activation('relu'))
Amodel.add(MaxPooling2D(pool_size=(2, 2)))

Amodel.add(Conv2D(100, (3,3)))
Amodel.add(Activation('relu'))
Amodel.add(MaxPooling2D(pool_size=(2, 2)))

Amodel.add(Dropout(0.3))
Amodel.add(Flatten())

Amodel.add(Dense(50, activation='relu'))
Amodel.add(Dense(12, activation='softmax'))

Amodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
cp = ModelCheckpoint('model-best', verbose=0, save_best_only=True)
model.fit(X_train, Y_train, epochs = 5, callbacks=[cp], validation_split=0.2)

Epoch 1/5
882/882 [==============================] - 1600s 2s/step - loss: 0.2724 - accuracy: 0.8876 - val_loss: 0.2430 - val_accuracy: 0.9074
INFO:tensorflow:Assets written to: model-best\assets
Epoch 2/5
882/882 [==============================] - 1382s 2s/step - loss: 0.1997 - accuracy: 0.9206 - val_loss: 0.1798 - val_accuracy: 0.9362
INFO:tensorflow:Assets written to: model-best\assets
Epoch 3/5
882/882 [==============================] - 1427s 2s/step - loss: 0.1612 - accuracy: 0.9393 - val_loss: 0.1922 - val_accuracy: 0.9307
Epoch 4/5
882/882 [==============================] - 1865s 2s/step - loss: 0.1379 - accuracy: 0.9488 - val_loss: 0.1729 - val_accuracy: 0.9399
INFO:tensorflow:Assets written to: model-best\assets
Epoch 5/5
882/882 [==============================] - 1478s 2s/step - loss: 0.1221 - accuracy: 0.9549 - val_loss: 0.1769 - val_accuracy: 0.9379


In [ ]:
#Age
cp = ModelCheckpoint('amodel-best', verbose=0, save_best_only=True)
Amodel.fit(AX_train, AY_train, epochs = 20, callbacks=[cp], validation_split=0.2)

Epoch 1/20
184/184 [==============================] - 520s 3s/step - loss: 2.2934 - accuracy: 0.1832 - val_loss: 1.8179 - val_accuracy: 0.3666
INFO:tensorflow:Assets written to: amodel-best\assets
Epoch 2/20
184/184 [==============================] - 488s 3s/step - loss: 1.7246 - accuracy: 0.3979 - val_loss: 1.6216 - val_accuracy: 0.4068
INFO:tensorflow:Assets written to: amodel-best\assets
Epoch 3/20
184/184 [==============================] - 492s 3s/step - loss: 1.4932 - accuracy: 0.4559 - val_loss: 1.4881 - val_accuracy: 0.4614
INFO:tensorflow:Assets written to: amodel-best\assets
Epoch 4/20
184/184 [==============================] - 499s 3s/step - loss: 1.3511 - accuracy: 0.5126 - val_loss: 1.4244 - val_accuracy: 0.4915
INFO:tensorflow:Assets written to: amodel-best\assets
Epoch 5/20
184/184 [==============================] - 547s 3s/step - loss: 1.2746 - accuracy: 0.5267 - val_loss: 1.4078 - val_accuracy: 0.5003
INFO:tensorflow:Assets written to: amodel-best\assets
Epoch 6/20
184/

In [ ]:
#Emotions
#EX_train = EX_train.reshape(len(EX_train), input_shape[0], input_shape[1], input_shape[2])
#EX_test  = EX_test.reshape(len(EX_test), input_shape[0], input_shape[1], input_shape[2])

cp = ModelCheckpoint('emodel-best', verbose=0, save_best_only=True)
Emodel.fit(EX_train, EY_train, epochs = 20, callbacks=[cp], validation_split=0.2)

Epoch 1/20
321/321 [==============================] - 486s 2s/step - loss: 1.0960 - accuracy: 0.4259 - val_loss: 1.0342 - val_accuracy: 0.4830
INFO:tensorflow:Assets written to: emodel-best\assets
Epoch 2/20
321/321 [==============================] - 477s 1s/step - loss: 0.9840 - accuracy: 0.5219 - val_loss: 0.9486 - val_accuracy: 0.5341
INFO:tensorflow:Assets written to: emodel-best\assets
Epoch 3/20
321/321 [==============================] - 599s 2s/step - loss: 0.9271 - accuracy: 0.5511 - val_loss: 0.9089 - val_accuracy: 0.5735
INFO:tensorflow:Assets written to: emodel-best\assets
Epoch 4/20
321/321 [==============================] - 779s 2s/step - loss: 0.9020 - accuracy: 0.5730 - val_loss: 0.8881 - val_accuracy: 0.5794
INFO:tensorflow:Assets written to: emodel-best\assets
Epoch 5/20
321/321 [==============================] - 576s 2s/step - loss: 0.8607 - accuracy: 0.6047 - val_loss: 0.8740 - val_accuracy: 0.5880
INFO:tensorflow:Assets written to: emodel-best\assets
Epoch 6/20
321/

In [ ]:
from keras.models import load_model

In [ ]:
mod = load_model('model-best')

In [ ]:
emod = load_model('emodel-best')

In [ ]:
amod = load_model('amodel-best')

In [ ]:
face_detect = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_default.xml')

In [ ]:
source = cv2.VideoCapture(0)
while 1:
    not_to_use, image = source.read()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    faces = face_detect.detectMultiScale(gray, 1.5, 1)
    for (x, y, w, h) in faces:
        face_roi = gray[y:y+w, x:x+h]
        resized_image = cv2.resize(face_roi, (100, 100))
        normalized_image = resized_image/255
        reshaped_face = np.reshape(normalized_image, (1, 100, 100, 1))
        result = mod.predict(reshaped_face)[0]
        eresult = emod.predict(reshaped_face)[0]
        aresult = amod.predict(reshaped_face)[0]
        k = aresult.argmin()

        if k==0:
            cv2.putText(image, "(0-2) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==1:
            cv2.putText(image, "(3-6) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==2:
            cv2.putText(image, "(7-11) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==3:
            cv2.putText(image, "(17-21) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==4:
            cv2.putText(image, "(12-16) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==5:
            cv2.putText(image, "(22-27) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==6:
            cv2.putText(image, "(28-35) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==7:
            cv2.putText(image, "(36-43) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==8:
            cv2.putText(image, "(44-50) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==9:
            cv2.putText(image, "(51-55) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==10:
            cv2.putText(image, "(56-60) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        elif k==11:
            cv2.putText(image, "(60+) years", (x, y+h+30), cv2.FONT_HERSHEY_SIMPLEX, 1, (230, 216, 173), 2)
        #print("Result : ", result)
        if result[0] >  result[1]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
            cv2.putText(image, "Male", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

        if result[1] >  result[0]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)
            cv2.putText(image, "Female", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

        if eresult[0] >  eresult[1]:
            if eresult[0] > eresult[2]:
                cv2.putText(image, "Neutral", (x+200, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (153, 255, 255), 2)
            else :
                cv2.putText(image, "Sad", (x+200, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (153, 255, 255), 2)


        else:
            if eresult[1] > eresult[2]:
                cv2.putText(image, "Happy", (x+200, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (153, 255, 255), 2)
            else :
                cv2.putText(image, "Sad", (x+200, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (153, 255, 255), 2)


    cv2.imshow('Verzeo Project', image)
    key = cv2.waitKey(1)
    if key == 27:
        break
cv2.destroyAllWindows()
source.release()